@extends('layouts.app', ['active' => 'inicio'])
@section('title', $titulo)
@section('content')
<section class="alpha-hero rounded-3xl p-6 sm:p-9 mb-6">
<p class="text-xs uppercase tracking-widest text-yellow-400 mb-4">{{ $guard === 'web' ? 'Control del gimnasio' : 'Tu entrenamiento, a tu ritmo' }}</p>
<h2 class="text-3xl sm:text-4xl font-bold mb-3">Hola, {{ $nombre }}.</h2>
<p class="text-gray-300 text-sm mb-6">Organiza tu día, sigue tus avances y haz que cada entrenamiento cuente.</p>
<div class="flex flex-wrap gap-3">@foreach($acciones as [$ruta, $etiqueta])<a href="{{ route($ruta) }}" class="{{ $loop->first ? 'alpha-btn-primary' : 'alpha-btn-secondary' }} px-5 py-3 rounded-xl text-sm">{{ $etiqueta }}</a>@endforeach</div>
</section>
<section class="grid grid-cols-2 xl:grid-cols-4 gap-4 mb-8" aria-label="Resumen de actividad">@foreach($metricas as [$etiqueta, $valor])<article class="alpha-card rounded-2xl p-5"><p class="text-xs text-gray-400 mb-3">{{ $etiqueta }}</p><p class="text-3xl font-bold tabular-nums">{{ $valor }}</p></article>@endforeach</section>
<div class="grid xl:grid-cols-2 gap-6"><section class="alpha-card rounded-2xl p-6"><div class="flex justify-between gap-3 mb-5"><h2 class="font-semibold text-lg">Mis rutinas</h2><a href="{{ route('entrenamientos.index') }}" class="text-xs text-yellow-400">Ver todas →</a></div>
@forelse($rutinas as $rutina)<a class="alpha-list-row" href="{{ route('entrenamientos.editar', $rutina) }}"><div><strong class="text-sm">{{ $rutina->nombre }}</strong><p class="text-xs text-gray-400 mt-1">{{ $rutina->dias_count }} días · {{ $rutina->nivel }}</p></div><span>↗</span></a>@empty<div class="py-8 text-center"><p class="font-medium mb-2">Tu primera rutina te espera</p><p class="text-sm text-gray-400 mb-5">Organiza tus ejercicios y días de entrenamiento.</p><form method="POST" action="{{ route('entrenamientos.crear') }}">@csrf<button class="alpha-btn-primary px-5 py-3 rounded-xl text-sm">Crear mi rutina</button></form></div>@endforelse</section>
@can('asistencia')<section class="alpha-card rounded-2xl p-6"><div class="flex justify-between gap-3 mb-5"><h2 class="font-semibold text-lg">Actividad reciente</h2><a href="{{ route('asistencia.index') }}" class="text-xs text-yellow-400">Ver historial →</a></div>@forelse($actividad as $visita)<div class="alpha-list-row"><div><strong class="text-sm">{{ $visita->cliente?->nombre ?? 'Miembro' }}</strong><p class="text-xs text-gray-400 mt-1">{{ $visita->fecha_hora->format('d/m/Y · H:i') }}</p></div><span class="text-xs text-gray-400">{{ $visita->fecha_salida ? 'Visita completada' : 'En el gimnasio' }}</span></div>@empty<p class="text-sm text-gray-400 py-10 text-center">Las próximas visitas aparecerán aquí.</p>@endforelse</section>@endcan</div>
@if($porVencer->isNotEmpty())<section class="alpha-card rounded-2xl p-6 mt-6"><h2 class="font-semibold mb-3">Planes que vencen en los próximos 7 días</h2>@foreach($porVencer as $plan)<a href="{{ route('membresias.index') }}" class="alpha-list-row text-sm"><span>{{ $plan->cliente->nombre }} · {{ $plan->plan }}</span><span class="text-yellow-400">{{ $plan->fin->format('d/m/Y') }}</span></a>@endforeach</section>@endif
@endsection
