@extends('layouts.app', ['active' => 'configuracion'])
@section('title', 'Mi cuenta')
@section('content')
<p class="text-sm text-gray-400 mb-6">Actualiza tus datos personales y protege tu acceso.</p>
<div class="grid lg:grid-cols-2 gap-6">
<section class="alpha-card rounded-2xl p-6"><h2 class="font-semibold text-lg mb-4">Datos personales</h2><p class="text-sm text-gray-400 mb-5">{{ $correo }} · {{ $rolEtiqueta }}<br>Cuenta desde {{ $miembroDesde }}</p>
<form method="POST" action="{{ route('configuracion.perfil') }}" class="alpha-form space-y-4">@csrf<label>Nombre *<input name="nombre" value="{{ old('nombre', $nombre) }}" maxlength="100" autocomplete="name" required></label><button class="alpha-btn-primary rounded-xl px-5 py-3 text-sm">Guardar perfil</button></form></section>
<section class="alpha-card rounded-2xl p-6"><h2 class="font-semibold text-lg mb-4">Foto de perfil</h2><div class="w-16 h-16 rounded-2xl overflow-hidden bg-white/5 flex items-center justify-center mb-4">@if($avatarUrl)<img src="{{ $avatarUrl }}" alt="Tu foto de perfil" width="64" height="64" decoding="async" class="w-full h-full object-cover">@else<span class="text-2xl">{{ mb_substr($nombre, 0, 1) }}</span>@endif</div><form method="POST" action="{{ route('configuracion.avatar') }}" enctype="multipart/form-data" class="alpha-form space-y-4">@csrf<label>Seleccionar imagen *<input type="file" name="avatar" accept="image/jpeg,image/png,image/webp" data-image-preview="profile-avatar-preview" required></label><img id="profile-avatar-preview" class="hidden w-24 h-24 rounded-2xl object-cover" alt="Vista previa de la foto seleccionada"><p class="text-xs text-gray-400">JPG, PNG o WebP, máximo 2 MB. Se optimiza y elimina metadatos al guardar.</p><button class="alpha-btn-primary rounded-xl px-5 py-3 text-sm">Guardar foto</button></form></section>
@include('partials.appearance-settings')
@if($guard === 'cliente' && !$esGoogle && !$usuarioActual->google_id)
<section class="alpha-card rounded-2xl p-6 lg:col-span-2"><h2 class="font-semibold text-lg mb-3">Vincular Google</h2><p class="text-sm text-gray-400 mb-4">Confirma tu contraseña y elige en Google la misma dirección de correo que usas aquí. Después podrás acceder de ambas formas.</p><form method="POST" action="{{ route('configuracion.google') }}" class="alpha-form flex flex-col sm:flex-row gap-4 sm:items-end">@csrf<label class="flex-1">Contraseña actual<input name="password_actual" type="password" autocomplete="current-password" required></label><button class="alpha-btn-secondary rounded-xl px-5 py-3">Continuar con Google</button></form></section>
@endif
<section class="alpha-card rounded-2xl p-6"><h2 class="font-semibold text-lg mb-4">Seguridad</h2>@unless($esGoogle)<form method="POST" action="{{ route('configuracion.password') }}" class="alpha-form space-y-4">@csrf<label>Contraseña actual *<input name="password_actual" type="password" autocomplete="current-password" required></label><label>Nueva contraseña *<input name="password" type="password" autocomplete="new-password" minlength="12" required></label><label>Confirmar nueva contraseña *<input name="password_confirmation" type="password" autocomplete="new-password" minlength="12" required></label><p class="text-xs text-gray-400">Usa al menos 12 caracteres, mayúsculas, minúsculas, un número y un símbolo. Las demás sesiones se cerrarán.</p><button class="alpha-btn-primary rounded-xl px-5 py-3 text-sm">Actualizar contraseña</button></form>@else<p class="text-sm text-gray-400">El acceso de esta cuenta se gestiona con Google.</p>@endunless</section>
<section class="alpha-card rounded-2xl p-6"><h2 class="font-semibold text-lg mb-4">Sesión</h2><p class="text-sm text-gray-400">Cierra tu sesión al terminar si utilizas un equipo compartido. Tu apariencia y tus entrenamientos seguirán guardados en tu cuenta.</p><form method="POST" action="{{ route($guard === 'web' ? 'logout' : 'cliente.logout') }}" class="mt-6 pt-5 border-t border-white/10">@csrf<button class="text-sm text-red-400">Cerrar sesión en este dispositivo</button></form></section>
</div>
@endsection
