@extends('layouts.app', ['active' => 'entrenadores'])
@section('title', 'Entrenadores')
@section('content')
@php($esAdmin = auth('web')->user()?->rol === 'Administrador')
@if($esAdmin)
<details class="alpha-card rounded-2xl p-5 mb-6" @if($errors->any()) open @endif><summary class="font-semibold cursor-pointer">＋ Agregar entrenador</summary><form method="POST" action="{{ route('entrenadores.store') }}" enctype="multipart/form-data" class="alpha-form grid sm:grid-cols-2 gap-4 mt-5">@csrf
<label>Nombre<input name="name" value="{{ old('name') }}" maxlength="255" autocomplete="name" required></label><label>Correo<input name="email" type="email" value="{{ old('email') }}" maxlength="255" autocomplete="email" required></label><label class="sm:col-span-2">Foto opcional (JPG, PNG o WebP, max. 2 MB)<input name="avatar" type="file" accept="image/jpeg,image/png,image/webp" data-image-preview="trainer-new-preview"></label><img id="trainer-new-preview" class="hidden w-24 h-24 rounded-2xl object-cover" alt="Vista previa"><div class="sm:col-span-2 text-xs text-gray-400">No se crea una contrasena compartida: el entrenador recibira un enlace privado para establecer la suya.</div><button class="alpha-btn-primary px-5 py-3 rounded-xl">Crear cuenta e invitar</button></form></details>
@endif
<p class="text-gray-400 text-sm mb-6">Conoce al equipo que acompana a los miembros.</p>
<div class="grid sm:grid-cols-2 xl:grid-cols-3 gap-5">
@forelse($entrenadores as $entrenador)<article class="alpha-card rounded-2xl p-6"><div class="w-20 h-20 rounded-2xl bg-yellow-400/10 flex items-center justify-center text-yellow-400 text-2xl font-bold mb-5 overflow-hidden">@if($entrenador->avatar_url)<img src="{{ $entrenador->avatar_url }}" alt="{{ $entrenador->name }}" loading="lazy" class="w-full h-full object-cover">@else{{ mb_substr($entrenador->name, 0, 1) }}@endif</div><h2 class="text-xl font-semibold">{{ $entrenador->name }}</h2><p class="text-sm text-gray-400 mt-2">Entrenador · {{ $entrenador->activo ? 'Cuenta activa' : 'Cuenta inactiva' }}</p>
@if($esAdmin)<details class="mt-4"><summary class="text-sm text-yellow-400 cursor-pointer">Editar entrenador</summary><form method="POST" action="{{ route('entrenadores.update', $entrenador) }}" enctype="multipart/form-data" class="alpha-form space-y-3 mt-4">@csrf @method('PUT')<label>Nombre<input name="name" value="{{ $entrenador->name }}" required></label><label>Correo<input type="email" name="email" value="{{ $entrenador->email }}" required></label><label>Acceso<select name="activo"><option value="1" @selected($entrenador->activo)>Activo</option><option value="0" @selected(!$entrenador->activo)>Inactivo</option></select></label><label>Cambiar foto<input type="file" name="avatar" accept="image/jpeg,image/png,image/webp" data-image-preview="trainer-{{ $entrenador->id }}-preview"></label><img id="trainer-{{ $entrenador->id }}-preview" class="hidden w-24 h-24 rounded-xl object-cover" alt="Vista previa">@if($entrenador->avatar)<label class="inline-flex items-center gap-2"><input type="checkbox" name="eliminar_avatar" value="1"> Eliminar foto actual</label>@endif<button class="alpha-btn-primary w-full rounded-xl px-4 py-3">Guardar cambios</button></form></details>@endif
</article>@empty<div class="alpha-card rounded-2xl p-10 sm:col-span-2 xl:col-span-3 text-center">No hay entrenadores registrados.</div>@endforelse
</div><div class="mt-6">{{ $entrenadores->links() }}</div>
<script>document.querySelectorAll('[data-image-preview]').forEach(input=>input.addEventListener('change',()=>{const image=document.getElementById(input.dataset.imagePreview);const file=input.files[0];if(!file){image.classList.add('hidden');return}image.src=URL.createObjectURL(file);image.classList.remove('hidden')}));</script>
@endsection
