<?php

$dato = fn (string $variable, string $marcador) => env($variable) ?: '{{'.$marcador.'}}';

return [
    'version' => env('LEGAL_VERSION', '2026-10-04') ?: '2026-10-04',
    'marcadores' => [
        'NOMBRE_RESPONSABLE' => $dato('LEGAL_NOMBRE_RESPONSABLE', 'NOMBRE_RESPONSABLE'),
        'DIRECCION_RESPONSABLE' => $dato('LEGAL_DIRECCION_RESPONSABLE', 'DIRECCION_RESPONSABLE'),
        'CORREO_PRIVACIDAD' => $dato('LEGAL_CORREO_PRIVACIDAD', 'CORREO_PRIVACIDAD'),
        'TELEFONO_RESPONSABLE' => $dato('LEGAL_TELEFONO_RESPONSABLE', 'TELEFONO_RESPONSABLE'),
        'PERSONA_CONTACTO_PRIVACIDAD' => $dato('LEGAL_PERSONA_CONTACTO', 'PERSONA_CONTACTO_PRIVACIDAD'),
        'PROVEEDORES_Y_PAISES' => $dato('LEGAL_PROVEEDORES_Y_PAISES', 'PROVEEDORES_Y_PAISES'),
        'PLAZO_RETENCION' => $dato('LEGAL_PLAZO_RETENCION', 'PLAZO_RETENCION'),
        'POLITICA_CANCELACIONES_Y_REEMBOLSOS' => $dato('LEGAL_CANCELACIONES', 'POLITICA_CANCELACIONES_Y_REEMBOLSOS'),
        'HORARIOS_Y_SERVICIOS' => $dato('LEGAL_HORARIOS_Y_SERVICIOS', 'HORARIOS_Y_SERVICIOS'),
        'PROCEDIMIENTO_ACCIDENTES' => $dato('LEGAL_PROCEDIMIENTO_ACCIDENTES', 'PROCEDIMIENTO_ACCIDENTES'),
    ],
];
