@extends('layouts.app', ['active' => 'membresias'])
@section('title', 'Membresias')
@section('content')
<p class="text-gray-400 text-sm mb-6">{{ $guard === 'cliente' ? 'Elige un plan y presenta el pago en recepcion. Solicitar no activa la membresia.' : 'Consulta solicitudes y membresias. Solo la secretaria puede confirmar cobros y activaciones.' }}</p>

@if($guard === 'cliente')
<section class="grid sm:grid-cols-2 xl:grid-cols-3 gap-4 mb-8">@foreach($planes as $plan)<article class="alpha-card rounded-2xl p-6"><h2 class="text-xl font-semibold">{{ $plan->nombre }}</h2><p class="text-3xl font-bold text-yellow-400 my-3">${{ number_format((float)$plan->precio, 2) }}</p><p class="text-sm text-gray-400">{{ $plan->duracion_dias }} dias · {{ $plan->condiciones }}</p><form method="POST" action="{{ route('membresias.solicitar') }}" class="mt-5">@csrf<input type="hidden" name="plan_id" value="{{ $plan->id }}"><button class="alpha-btn-primary rounded-xl px-5 py-3 w-full">Solicitar este plan</button></form></article>@endforeach</section>
@else
<form method="GET" class="alpha-card alpha-form rounded-2xl p-5 mb-6 grid sm:grid-cols-3 gap-3"><label>Cliente<input name="q" value="{{ $busqueda }}" placeholder="Nombre o correo"></label><label>Estado<select name="estado"><option value="">Todos</option>@foreach(['pendiente','activada','cancelada'] as $opcion)<option value="{{ $opcion }}" @selected($estado === $opcion)>{{ ucfirst($opcion) }}</option>@endforeach</select></label><div class="flex items-end gap-2"><button class="alpha-btn-primary px-4 py-3 rounded-xl">Filtrar</button><a href="{{ route('membresias.index') }}" class="py-3 text-sm">Limpiar</a></div></form>
@endif

<h2 class="text-lg font-bold mb-4">Solicitudes</h2>
<div class="grid sm:grid-cols-2 xl:grid-cols-3 gap-4 mb-6">@forelse($solicitudes as $solicitud)<article class="alpha-card rounded-2xl p-5"><div class="flex justify-between gap-3"><div><p class="font-semibold">{{ $solicitud->plan_nombre }}</p><p class="text-xs text-gray-400">{{ $solicitud->cliente->nombre }}</p></div><span class="text-xs text-yellow-400">{{ ucfirst($solicitud->estado) }}</span></div><p class="text-2xl font-bold mt-3">${{ number_format((float)$solicitud->precio_acordado, 2) }}</p><p class="text-xs text-gray-400 mt-1">{{ $solicitud->duracion_dias }} dias · condiciones guardadas al solicitar</p>
@if($solicitud->estado === 'pendiente' && auth('web')->user()?->rol === 'Secretaria')<form method="POST" action="{{ route('membresias.activar', $solicitud) }}" class="alpha-form mt-4 space-y-3">@csrf @method('PATCH')<label>Importe cobrado<input type="number" name="importe" min="0.01" step="0.01" value="{{ $solicitud->precio_acordado }}" required></label><label>Referencia opcional<input name="referencia" maxlength="100"></label><button class="alpha-btn-primary w-full rounded-xl px-4 py-3">Confirmar pago y activar</button></form>@endif
@if($solicitud->estado === 'pendiente' && ($guard === 'cliente' || auth('web')->user()?->rol === 'Secretaria'))<form method="POST" action="{{ route('membresias.solicitudes.cancelar', $solicitud) }}" class="mt-3">@csrf @method('PATCH')<button class="text-sm text-red-300">Cancelar solicitud</button></form>@endif
@if($solicitud->membresia?->pago)<p class="text-xs text-gray-400 mt-4">Cobrado {{ $solicitud->membresia->pago->pagado_en->format('d/m/Y H:i') }} por {{ $solicitud->membresia->pago->registrador?->name ?? 'Personal anterior' }}</p>@endif
</article>@empty<div class="alpha-card rounded-2xl p-8 text-gray-400 sm:col-span-2 xl:col-span-3">No hay solicitudes con estos filtros.</div>@endforelse</div>
{{ $solicitudes->links() }}

<h2 class="text-lg font-bold mt-8 mb-4">Historial de membresias</h2>
<div class="overflow-x-auto alpha-card rounded-2xl"><table class="w-full text-sm"><thead><tr class="text-left text-gray-400 border-b border-white/10"><th class="p-4">Cliente</th><th class="p-4">Plan</th><th class="p-4">Vigencia</th><th class="p-4">Estado</th><th class="p-4">Pago</th></tr></thead><tbody>@forelse($membresias as $membresia)<tr class="border-b border-white/5"><td class="p-4">{{ $membresia->cliente->nombre }}</td><td class="p-4">{{ $membresia->plan }}</td><td class="p-4">{{ $membresia->inicio->format('d/m/Y') }} - {{ $membresia->fin->format('d/m/Y') }}</td><td class="p-4">{{ $membresia->estado }}</td><td class="p-4">${{ number_format((float)$membresia->importe, 2) }}@if($membresia->pago)<br><span class="text-xs text-gray-400">{{ $membresia->pago->pagado_en->format('d/m/Y H:i') }}</span>@endif</td></tr>@empty<tr><td colspan="5" class="p-8 text-center text-gray-400">No hay membresias.</td></tr>@endforelse</tbody></table></div><div class="mt-5">{{ $membresias->links() }}</div>
@endsection
