@extends('layouts.app', ['active' => 'cuentas'])
@section('title', $personal ? 'Personal del gimnasio' : 'Clientes')
@section('eyebrow', 'Gestion de cuentas')
@section('content')
<p class="text-sm text-gray-400 mb-6">Administra datos basicos y acceso. Una cuenta inactiva conserva su historial y no puede usar una sesion existente.</p>
@can('administrar')<nav class="flex gap-3 mb-6"><a href="{{ route('cuentas.index') }}" class="{{ !$personal ? 'alpha-btn-primary' : 'alpha-btn-secondary' }} px-4 py-2 rounded-xl text-sm">Clientes</a><a href="{{ route('cuentas.index', ['tipo' => 'personal']) }}" class="{{ $personal ? 'alpha-btn-primary' : 'alpha-btn-secondary' }} px-4 py-2 rounded-xl text-sm">Personal</a></nav>@endcan

@if($personal && \Illuminate\Support\Facades\Gate::allows('administrar'))
<details class="alpha-card rounded-2xl p-5 mb-5" @if($errors->any()) open @endif><summary class="font-semibold cursor-pointer">＋ Registrar empleado</summary><form method="POST" action="{{ route('cuentas.store') }}" class="alpha-form grid sm:grid-cols-2 gap-4 mt-5">@csrf<label>Nombre *<input name="nombre" value="{{ old('nombre') }}" maxlength="100" required autocomplete="name"></label><label>Correo *<input type="email" name="correo" value="{{ old('correo') }}" maxlength="255" required autocomplete="email"></label><label>Rol *<select name="rol" required>@foreach(\App\Support\Acceso::ROLES_ASIGNABLES as $rol)<option @selected(old('rol', 'Secretaria') === $rol)>{{ $rol }}</option>@endforeach</select></label><div class="sm:col-span-2 text-xs text-gray-400">La persona recibira un enlace privado para establecer su contrasena. La clave nunca se muestra ni se comparte.</div><div><button class="alpha-btn-primary px-5 py-3 rounded-xl">Crear cuenta e invitar</button></div></form></details>
@elseif(!$personal && \Illuminate\Support\Facades\Gate::allows('administrar'))
<p class="alpha-card rounded-2xl p-5 mb-5 text-sm text-gray-400">Los clientes crean su propia cuenta desde el registro publico. Aqui puedes activar o desactivar su acceso.</p>
@endif

<form method="GET" class="alpha-form flex flex-col sm:flex-row gap-3 mb-5"><input type="hidden" name="tipo" value="{{ $personal ? 'personal' : 'cliente' }}"><input type="search" name="q" value="{{ $q }}" maxlength="100" placeholder="Nombre o correo" class="flex-1"><select name="estado"><option value="">Todos los estados</option><option value="activo" @selected($estado === 'activo')>Activas</option><option value="inactivo" @selected($estado === 'inactivo')>Inactivas</option></select><button class="alpha-btn-secondary px-5 py-3 rounded-xl">Filtrar</button></form>
<p class="text-xs text-gray-400 mb-3">{{ $cuentas->total() }} cuentas · Pagina {{ $cuentas->currentPage() }} de {{ $cuentas->lastPage() }}</p>
<div class="alpha-card rounded-2xl divide-y divide-white/10">
@forelse($cuentas as $cuenta)<article class="p-5"><div class="flex flex-wrap justify-between gap-4"><div><h2 class="font-semibold">{{ $cuenta->$campoNombre }}</h2><p class="text-sm text-gray-400">{{ $cuenta->$campoCorreo }}</p></div><span class="text-xs {{ $cuenta->activo ? 'text-green-400' : 'text-gray-400' }}">{{ $cuenta->activo ? 'Activa' : 'Inactiva' }}{{ $personal ? ' · '.$cuenta->rol : '' }}</span></div>
@can('administrar')<details class="mt-3"><summary class="text-sm text-yellow-400 cursor-pointer">Editar cuenta</summary><form method="POST" action="{{ route('cuentas.update', [$personal ? 'personal' : 'cliente', $cuenta->id]) }}" class="alpha-form grid sm:grid-cols-3 gap-4 mt-4">@csrf @method('PUT')<label>Nombre *<input name="nombre" value="{{ $cuenta->$campoNombre }}" required maxlength="100"></label><label>Acceso<select name="activo" @disabled($personal && $cuenta->rol === 'Administrador')><option value="1" @selected($cuenta->activo)>Activo</option><option value="0" @selected(!$cuenta->activo)>Inactivo</option></select>@if($personal && $cuenta->rol === 'Administrador')<input type="hidden" name="activo" value="1">@endif</label>@if($personal)<label>Rol<select name="rol" @disabled($cuenta->rol === 'Administrador')>@foreach($cuenta->rol === 'Administrador' ? ['Administrador'] : \App\Support\Acceso::ROLES_ASIGNABLES as $rol)<option @selected($cuenta->rol === $rol)>{{ $rol }}</option>@endforeach</select>@if($cuenta->rol === 'Administrador')<input type="hidden" name="rol" value="Administrador">@endif</label>@endif<div><button class="alpha-btn-primary px-4 py-2 rounded-xl text-sm">Guardar cambios</button></div></form>@if($personal && !$cuenta->password_establecida)<form method="POST" action="{{ route('cuentas.invitar', $cuenta) }}" class="mt-3">@csrf<button class="text-sm text-yellow-400">Reenviar invitacion de contrasena</button></form>@endif</details>@endcan
</article>@empty<div class="p-10 text-center text-gray-400">No se encontraron cuentas.</div>@endforelse</div><div class="mt-5">{{ $cuentas->links() }}</div>
@endsection
